version: '3'

services:
#  mongo:
#    container_name: 'mongo'
#    restart: unless-stopped
#    image: mongodb/mongodb-community-server:7.0.8-ubuntu2204
#    environment:
#      - MONGODB_INITDB_ROOT_USERNAME=root
#      - MONGODB_INITDB_ROOT_PASSWORD=password
#    ports:
#      - 27017:27017
  mongo:
    container_name: 'mongo'
    restart: unless-stopped
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - 27017:27017
  mongo-express:
    container_name: 'mongo-express'
    restart: unless-stopped
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
    ports:
      - 8081:8081